---
- name: Install ClickHouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Start ClickHouse service
      ansible.builtin.service:
        name: clickhouse-server.service
        state: restarted

  tasks:
    - name: Install ClickHouse packages directly from the repository
      ansible.builtin.yum:
        name:
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-client-{{ clickhouse_version }}.noarch.rpm"
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-server-{{ clickhouse_version }}.noarch.rpm"
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
        disable_gpg_check: true

    - name: Reload systemd manager configuration
      ansible.builtin.shell: systemctl daemon-reload

    - name: Ensure ClickHouse service is enabled and started
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: true

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  tags: vector
  become: true
  handlers:
    - name: Restart Vector service
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Install Vector package directly from the repository
      ansible.builtin.yum:
        name: "https://yum.vector.dev/stable/vector-0/x86_64/vector-{{ vector_rpm_version }}.x86_64.rpm"
        disable_gpg_check: true

      notify: Restart Vector service

    - name: Replace Vector configuration file
      ansible.builtin.template:
        src: templates/config/vector.toml.j2
        dest: /etc/vector/vector.yaml
        owner: admin
        group: admin
        mode: "0644"
      notify: Restart Vector service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

- name: Install Lighthouse
  tags: lighthouse
  hosts: lighthouse
  handlers:
    - name: Start nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.yum:
        name: "{{ item }}"
      with_items: "{{ necessary_packages }}"
    - name: Get Lightkhouse Archive
      ansible.builtin.get_url:
        url: "{{ lighthouse_link }}"
        dest: ./lighthouse.zip
        mode: '0644'
    - name: Unpack Lighthouse Archive
      become: true
      ansible.builtin.unarchive:
        src: ./lighthouse.zip
        dest: /usr/share/nginx
        remote_src: true
    - name: Copy nginx configuration file
      become: true
      ansible.builtin.template:
        src: nginx_lighthouse.conf
        dest: "/etc/nginx/conf.d/lighthouse.conf"
        owner: "0"
        group: "0"
        mode: "0664"
      notify: Start nginx service
