{
 "title": "task2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": " CPULA 1/5/15 (Load Average)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA 1" },
    { "expr": "node_load5", "legendFormat": "CPULA 5" },
    { "expr": "node_load5", "legendFormat": "CPULA 15" }
   ]
  },
  {
   "title": "Утилизация CPU (в процентах, 100 - idle)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\r"
    }
   ]
  },
  {
   "title": "количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"} / 1024 / 1024 / 1024"
    }
   ]
  }
 ]
}