---
- name: Install ClickHouse
  hosts: clickhouse
  tags: clickhouse
  become: true
  handlers:
    - name: Start ClickHouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Install ClickHouse packages directly from the repository
      ansible.builtin.yum:
        name:
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-client-{{ clickhouse_version }}.noarch.rpm"
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-server-{{ clickhouse_version }}.noarch.rpm"
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
        disable_gpg_check: true

      notify: Start ClickHouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0


- name: Install Vector
  hosts: vector
  tags: vector
  become: true
  handlers:
    - name: Restart Vector service
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Install Vector package directly from the repository
      ansible.builtin.yum:
        name: "https://yum.vector.dev/stable/vector-0/x86_64/vector-{{ vector_rpm_version }}.x86_64.rpm"
        disable_gpg_check: true

      notify: Restart Vector service

    - name: Replace Vector configuration file
      ansible.builtin.template:
        src: templates/config/vector.toml.j2
        dest: /etc/vector/vector.yaml
        owner: admin
        group: admin
        mode: "0644"
      notify: Restart Vector service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
